### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### User show (user homepage)
GET http://localhost:3000/users/4
Content-Type: application/json

###user update
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
  "name":"Aspen",
  "email":"aspen11@mail.com"
}