@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzU4NjgxOTh9.EOPFxVK8tFzuQCZ7xHpgg0_wY5ZPZd7NICax4CmTsF4
@hostname = http://localhost:3000

### Sessions create (login)
POST {{hostname}}/sessions
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "email": "tay1@mail.com",
  "password": "password"
}

### Users create (signup)
POST {{hostname}}/users
Content-Type: application/json

{
  "name": "Baby Yoda",
  "email": "grogu@mail.com",
  "password": "password",
  "password_confirmation": "password"
}

### User show (user homepage)
GET {{hostname}}/users/me
Content-Type: application/json
Authorization: Bearer {{jwt}}

###user update
PATCH {{hostname}}/users/me
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "image_url":"https://images.static-ziprealty.com/z/1629483439000/images_personnel/v3/BHG/7983/240071/ta/tayja.joshua/medium.jpeg"
}

###user destroy
DELETE {{hostname}}/users/me
Content-Type: application/json
Authorization: Bearer {{jwt}}

###post index
GET {{hostname}}/posts
Content-Type: application/json

###post create 
POST {{hostname}}/posts
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "blurb": "crystalssss for days",
  "image_url": "cool pic here",
  "video_url": "sweet video"
}

###post show
GET {{hostname}}/posts/1
Content-Type: application/json

###post update
PATCH {{hostname}}/posts/8
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "blurb": "crystals for days!!!!",
  "blog": "all the cool crystals info right here"
}

###comment create
POST {{hostname}}/comments
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "post_id": 8,
  "body": "wowww",
  "image_url": "cute pic"
}

###comment show
GET {{hostname}}/comments/2
Content-Type: application/json

###comment update
PATCH {{hostname}}/comments/7
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "body": "this is kinda funny",
  "image_url": "funnier gif"
}

###comment destroy
DELETE {{hostname}}/comments/7
Content-Type: application/json
Authorization: Bearer {{jwt}}

###board index
GET {{hostname}}/boards
Content-Type: application/json
Authorization: Bearer {{jwt}}

###board create
POST {{hostname}}/boards
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "meditation stuff"
}

###board show
GET {{hostname}}/boards/3
Content-Type: application/json

###board update
PATCH {{hostname}}/boards/1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "good vibess"
}

###board destroy
DELETE {{hostname}}/boards/4
Content-Type: application/json
Authorization: Bearer {{jwt}}

###post_board create
POST {{hostname}}/post_boards
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "post_id": 4,
  "board_id":6
}

###post_board destroy
DELETE {{hostname}}/post_boards/10
Content-Type: application/json
Authorization: Bearer {{jwt}}